services:
  signaloneui:
    image: '322456/signaloneui:dev'
    ports:
      - "80:80"
    depends_on:
      - signaloneapi
  signaloneapi:
    image: '322456/signaloneapi:dev'
    volumes:
      - ./data/issues:/data
    depends_on:
      - signalonemlworker
    ports:
      - "8000:8000"
  signalonemlworker:
    image: '322456/signalonemlworker:dev'
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/issues:/data
