version: '3'
services:

  backend:
    image: '322456/signalonebackend:dev'
    ports:
      - 8080:8080
    depends_on:
      - qdrant-db
      - mongo-db

  qdrant-db:
      image: qdrant/qdrant
      ports:
        - 6334:6334
      volumes:
        - ./qdrant-data:/qdrant_data
      
  mongo-db:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - ./mongo-data:/data/db
