version: '3'
services:

  backend:
    image: '322456/signalonebackend:dev'
    ports:
      - 8080:8080
    depends_on:
      - qdrant-db
      - mongo-db

  qdrant-db:
      image: qdrant/qdrant
      ports:
        - 6333:6333
      volumes:
        - ./qdrant-data:/qdrant/storage
      
  mongo-db:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - ./mongo-data:/data/db
