services:
  signaloneui:
    image: '322456/signaloneui:dev'
    ports:
      - "80:80"
    depends_on:
      - signaloneapi
  signalonemlworker:
    image: '322456/signalonemlworker:dev'
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/issues:/data
