services:
  # signalonefrontend:
  #   image: '322456/signalonefrontend:dev'
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - signaloneagent
  signaloneagent:
    restart: unless-stopped
    image: '322456/signalone-extension:dev'
