services:
  signalonefrontend:
    image: '322456/signalonefrontend:dev'
    ports:
      - "37001:37001"
    depends_on:
      - signaloneagent
  signaloneagent:
    restart: unless-stopped
    image: '322456/signalone-extension:dev'
